### ISSUE TITLE
Cleanup tasks

### ISSUE THREAD

**Issue by rbrito** [coursera-dl/coursera-dl#118]
This bug is meant to act as a grab bag of other bugs of things that I want to have fixed in our code. I will keep updating it with pointers to respective tickets. Comments and criticism are welcome.
- [x] Move from messy `urllib2` to `requests` (issue #76).
- [x] Move _local_ credential information (netrc, passwords, etc) to a module. (issue #128)
- [x] Move _external_ credential information (grabbing tokens, etc) to a module?
- [x] Move filesystem related tasks (creating directories, checking if files exist) to a module?
- [x] Remove our homebrew (and increasingly bloated) downloader (it has grown even one class!) and substitute with another downloader (perhaps an adaptation of the downloader from `youtube-dl`). (issue #92)
- [x] Refactor choosing of downloader backend.
- [x] Allow the user to specify only `--aria2` to use `aria2c` (in the default paths) instead of having to specify which binary to run. Do the same for the other downloaders.
- [ ] Remove so many functions from inside of `download_lectures`. They should be covered by tests also.
- [ ] Kill downlading with `axel`? (issue #82)
