### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by balta2ar** [coursera-dl/coursera-dl#546]
Below are preliminary plans for things to do in release 0.7.0.

- [x] remove support for old-style courses (Coursera shut down old courses anyway)
- [x] remove `--ignore-http-errors` and make its behavior default
- [x] implement quiz downloading and conversion to HTML for Coursera on-demand courses #490
- [x] multi-threaded download (resources only, not syllabus) #85 #313 Implementation: #553
- [x] `--list-courses` option to list currently enrolled courses #514
- [x] download assignments not listed in the Course Content (#555)

In release plans I usually prefer to put something that resembles features and visible changes. I don't put refactoring and bugfixes (except maybe huge ones).

@rbrito Another thing. I'm still thinking about https://github.com/coursera-dl/edx-dl/issues/77. I've registered mooc-dl package on PyPI. I hope we can put common code from coursera-dl and edx-dl there and quietly, under-the-hood, transition to it.

Let's not make loud statements but rather take small steps towards implementing it. I'm not sure how much time I can devote to it (new amazing courses on Coursera and EDX are coming up again and again) but at least let's make this first step. @rbrito Could you please create `mooc-dl` repository in this organization and grant me read-write access? Generally, I think youtube-dl and you-get projects should be inspiring for us and we should learn from them.

**Comment by doublelduob** [comment]
pip can not find 0.7.0 version, how can I install this version ?

**Comment by laventura** [comment]
Hi @balta2ar, @rbrito - 
- What's the argument format for downloading content based on the NEW platform (not the one based on https://class.coursera.org/) ?  
- Is this documented somewhere?

Thx

**Comment by balta2ar** [comment]
@laventura There is no such an argument. The script will be downloading new format only in the next version.

**Comment by balta2ar** [comment]
Released 0.7.0.
